PREFIX schema: <http://schema.org/>

construct {
    ?uri schema:subEvent
        [ a schema:Event  ; 
        schema:name ?name ; 
        schema:description ?description ;
        schema:startDate ?dates ;
        schema:location ?location ]
}
where { 
    ?uri schema:description ?description ; 
    schema:location ?location ;
    schema:name ?name .
        { select ?dates where {
            values ?uri {  }
            ?uri  schema:startDate ?dates
        }
    } 
}